### ISSUE TITLE
Open Source

### ISSUE THREAD

**Issue by billinghamj** [intercom/intercom-ios#119]
You guys have made it clear that you want to open source this SDK - https://github.com/intercom/intercom-ios/issues/112#issuecomment-159967839

Could you please leave this issue open until you have done so? The issue is not resolved yet, so should not be closed.

**Comment by jtreanor** [comment]
Hi @billinghamj,

As you rightly point out, we have previously stated our desire to pursue this. However, due to a number of factors, we have not made any commitment to provide the source to date.

We see this as a feature request rather than an issue with the current release. For that reason I am closing this issue. If you have any more questions I would be happy to answer them, either here or at team@intercom.io.

Thank for for sharing your thoughts on this with us.

**Comment by matijakregar** [comment]
Would you at least consider exposing more features in the SDK? Maybe enough that would allow developers to implement custom UI. Or at least have a bit more customisation options ... like background color, font, textcolor etc..
