### ISSUE TITLE
No way to customize horizontal position of incoming message bubble

### ISSUE THREAD

**Issue by colinhumber** [intercom/intercom-ios#151]
The 2.x versions included an API for positioning the incoming preview bubble in one of 3 corners, as well as the x and y preview bubble padding. The current 3.x version deprecated both those APIs and made them non-functional preventing any customizations, which makes it impossible to customize the in-app experience for our designs.

## Version info
  - Intercom for iOS version: 3.0.3
  - iOS version: 9.3

## Expected behavior
The ability to customize the bubble position, both x and y

## Actual behavior
No such APIs exist anymore

## Steps to reproduce
N/A

## Logs

**Comment by jtreanor** [comment]
Hi @colinhumber,

Sorry to hear that you're disappointed by this omission. We removed the mentioned functionality in order to give the best possible consistent experience within the system we designed for the new Messenger.

However, I do understand why you may need this feature and we will certainly consider this need going forward.

There is one new API that partially fulfils your request, but only in the y direction: `[Intercom setBottomPadding:]`.

As this is a feature request, I will close this issue.

If you have any more questions about this, feel free to contact team@intercom.io.

**Comment by colinhumber** [comment]
Unfortunately this is keeping us from adopting the new SDK as our designs don't work with the new bubble layout.
