### ISSUE TITLE
Carthage doesn't work.

### ISSUE THREAD

**Issue by JamieWhite** [intercom/intercom-ios#173]
Your `README` suggests you support Carthage but when I try building it I get this error

```
*** Skipped building intercom-ios due to the error:
Dependency "intercom-ios" has no shared framework schemes for any of the platforms: iOS

If you believe this to be an error, please file an issue with the maintainers at https://github.com/intercom/intercom-ios/issues/new
```

I've forked your repo thinking perhaps you just need to share a scheme. Looks like you don't even have a `.xcodeproj` to build from which suggests to me you've never had Carthage support and you've never tested it to see this.

**Comment by JamieWhite** [comment]
Okay I see how you've done this now. You're hosting the binaries in your `Releases` tab. This command should work:

`carthage update intercom-ios --no-use-binaries`

but it doesn't because you have no `.xcodeproj` to build from. As a Swift developer I use `--no-use-binaries` to always build from scratch because Swift doesn't have a stable ABI so using the hosted binaries is a bad idea for now.

**Comment by jtreanor** [comment]
Hi @JamieWhite,

Unfortunately the source code for Intercom for iOS is not publicly available so the only option for using it is to use the provided binaries.

Having said that, the binaries we provide do not rely on Swift's ABI since it is written in Objective C. This means you can reliably use it across Swift versions.

**Comment by jtreanor** [comment]
Closing this issue because Intercom does work as expected with Carthage using a [prebuilt framework](https://github.com/Carthage/Carthage#archive-prebuilt-frameworks-into-one-zip-file). As mentioned above the prebuilt framework does not use Swift so is not bound to the ABI.

I'd be happy to answer any questions you have.
