### ISSUE TITLE
Messenger view is presenting instead of MessageComposer

### ISSUE THREAD

**Issue by Komal2905** [intercom/intercom-ios#176]
Please use the following template to submit your issue. Following this template will allow us to quickly investigate and help you with your issue. Please be aware that issues which do not conform to this template may be closed.

For feature requests please contact us at team@intercom.io

## Version info
  - Intercom for iOS version: 3.0.12
  - iOS version: 9.3

## Expected behavior
Must show  MessageComposer

## Actual behavior
it is showing  Messenger view even if call presentMessageComposer()

## Steps to reproduce
 1. 
 2. 
 3. 

## Logs

**Comment by bboyle18** [comment]
Hi @Komal2905 👋 

Thanks for getting in touch.
The reason for this is probably because you don't have inbound messaging enabled on your Intercom account. This feature is only available if you are using Intercom's [Resolve](https://www.intercom.com/customer-support) product.
If you check your logs, you should see something like this 

`INFO - You do not appear to have inbound messaging enabled on your Intercom account. Showing the Conversation list instead. If you wish to enable inbound messaging, please upgrade your account in Intercom.`

Hope this helps

Brian

**Comment by Komal2905** [comment]
@bboyle18 NO I am not getting this Log

**Comment by bboyle18** [comment]
We'll need a little more info in order to help you resolve your issue.
Can you turn on logging `[Intercom enableLogging];` and check the logs then?

Cheers

Brian

**Comment by Komal2905** [comment]
@bboyle18  

done following

func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) -> Bool
 {

Intercom.setApiKey(INETERCOM_API_KEY, forAppId: INTERCOM_APP_ID)
  Intercom.setLauncherVisible(true)
Intercom.enableLogging()
return true
}


but There is no Log as you said

**Comment by bboyle18** [comment]
Hey @Komal2905 
Can you contact us through Intercom to discuss this please? 
We'll be able to look into your account details to help us identify the issue you are having.

Thanks

Brian
