### ISSUE TITLE
Pod install does not seem happy after v3.0.9

### ISSUE THREAD

**Issue by emes** [intercom/intercom-ios#180]
## Version info
  - Intercom for iOS version: 3.0.12
  - iOS version: 10.0.2
  - pod version: 1.0.1

## Expected behavior

Podfile: 

```
target Xecfive do
      pod 'Intercom', :git => 'https://github.com/intercom/intercom-ios.git', :commit => '9266f57f8f90fe7a377e12a124368c1e94f9a2fa'
end
```

Update Intercom to v3.0.9 

```
$ pod update Intercom
-> Using Intercom (3.0.9)

$ ls -o Pods/Intercom
total 32
drwxr-xr-x  9 xs    306 Sep 27 19:37 Intercom.framework
drwxr-xr-x  3 xs    102 Sep 27 19:37 Intercom.framework.dSYM
-rwxr-xr-x  1 xs  11344 Sep 27 19:37 LICENSE
-rwxr-xr-x  1 xs   3702 Sep 27 19:37 README.md
```

## Actual behavior

Podfile: 

```
target Xecfive do
      pod 'Intercom', :git => 'https://github.com/intercom/intercom-ios.git', :commit => 'f6064833a1d6bda111643cfc90fa1b2c5b168c4f'
end
```

Update Intercom to v3.0.10, v.3.0.11 or v3.0.12 

```
$ pod update Intercom --verbose
-> Using Intercom (3.0.12)
       [!] Unable to read the license file `/Users/xs/src/pr/ios/Pods/Intercom/Intercom/LICENSE` for the spec `Intercom (3.0.12)`

$ ls -o Pods/Intercom
total 16
-rwxr-xr-x  1 xs  5685 Sep 27 19:51 README.md
```

## Steps to reproduce
 1. pod update Intercom (with a version after 3.0.9)

**Comment by jtreanor** [comment]
Hi @emes,

The reason you are seeing this error is because the podspec for Intercom [no longer points to the git repo](https://github.com/intercom/intercom-ios/blob/master/Intercom.podspec#L12), so using the `:git` directive will not work.

To solve this, you can update you Podfile to contain something like this:

```
target Xecfive do
      pod 'Intercom', '~> 3.0.12'
end
```

I see how this can be confusing. We will consider removing `Intercom.podspec` from the repo for clarity.
