### ISSUE TITLE
Enable to control the prompt tone

### ISSUE THREAD

**Issue by duguguiyu** [intercom/intercom-ios#228]
Please use the following template to submit your issue. Following this template will allow us to quickly investigate and help you with your issue. Please be aware that issues which do not conform to this template may be closed.

For feature requests please contact us at team@intercom.io

## Version info
  - Intercom for iOS version: 3.0.x
  - iOS version: any

## Expected behavior
Enable to control the prompt tone

## Actual behavior
Not support yet

## Logs

**Comment by bboyle18** [comment]
Hi @duguguiyu 👋

Just to confirm, it's the message alert audio that you want to be able to control? 
If so, what type of control do you want over it? The ability to have your own tone, mute it or both?

I'll include you're response as a feature request so that we can consider it for a future release 👍🏻

Cheers

Brian

**Comment by duguguiyu** [comment]
yeah, both. maybe, mute is more import ~~
