### ISSUE TITLE
Close alert window?

### ISSUE THREAD

**Issue by duguguiyu** [intercom/intercom-ios#229]
Please use the following template to submit your issue. Following this template will allow us to quickly investigate and help you with your issue. Please be aware that issues which do not conform to this template may be closed.

For feature requests please contact us at team@intercom.io

## Version info
  - Intercom for iOS version: 3.x
  - iOS version: any

## Expected behavior
Enable close alert window in settings.

## Actual behavior
Unable close alert window in settings.

## Steps to reproduce
 1. 
 2. 
 3. 

## Logs

**Comment by skylerwshaw** [comment]
Hey Huaiyu Fan, thanks for the message. 

Unfortunately it's unclear what you're wanting from your description. Which alert window do you want to close?

Since this is a feature request and not a feature, can you please message us from within your Intercom dashboard, or at team@intercom.com? Feel free to reference my name!

Best, Skyler
