### ISSUE TITLE
There is no registerUser call that allows attributes input (like Android library)

### ISSUE THREAD

**Issue by NicholasKirsten** [intercom/intercom-ios#230]
## Version info
  - Intercom for iOS version: 3.0.22
  - iOS version: 10.2.1

## Expected behavior
In the Android Intercom library there is a registerUser method that allows custom attributes to be sent with the register call to Intercom. This allows for the user details to be sent along with the register call so that there is only 1 call made to the server
## Actual behavior
On iOS you have to do 2 separate calls to first registerUser then updateUser in order to insert custom attributes. The problem this is causing is that we have Intercom Slack integration and our Directors use the slack channel to see intercom users being created. Because iOS does this in 2 calls the user's details are not updated before the Slack notification is fired which leads to the line "26B9CDE8-81F4-481A-8237-3F7A2568801B signed up as a new user" instead of having the user's name.

Sometimes however the timing is such that the user's details are updated in Intercom before the Slack notification is fired which shows the user's name correctly so our directors do not understand why this does occur for every registration.

## Steps to reproduce
 1. Add Intercom Slack integration
 2. Register a new user in iOS
 3. Update the user's details
 4. Note that the user's name is not displayed in Slack

## Logs

**Comment by skylerwshaw** [comment]
This was addressed in an Intercom conversation started at the same time as this issue was opened.

When calling `registerUnidentifiedUser`, indicating that you don't have user identifying information including `user_id` or `email`, Intercom creates a user with a pseudonym and auto generated UUID-type `user_id` (e.g. `26B9CDE8-81F4-481A-8237-3F7A2568801B`). This will fire on the `user created` webhook and Slack integration. If `registerUserWithUserId` or `registerUserWithEmail` is later called, the user will have these identifying attributes added but they will not be considered a wholly new user, preventing the same `user created` webhook from firing. We're currently looking into having Unidentified Users generated as Leads, which would allow webhooks to fire on Lead -> User migration.

**Comment by NicholasKirsten** [comment]
Thanks Skyler for quick and concise response times in regards to helping us with our issue
