### ISSUE TITLE
[Issue] IntercomUnreadConversationCountDidChangeNotification

### ISSUE THREAD

**Issue by lucianocn** [intercom/intercom-ios#248]
If the application is returning from background should automatically trigger ``IntercomUnreadConversationCountDidChangeNotification `` on ``UIApplicationDidBecomeActiveNotification``, because the count can changed.

I tried to manually fix adding a observer to ``UIApplicationDidBecomeActiveNotification``:
```objective-c
[[NSNotificationCenter defaultCenter]addObserver:self selector:@selector(updateUnreadCount) name:UIApplicationDidBecomeActiveNotification object:nil];
```
But ``[Intercom unreadConversationCount]`` is not returning the real value (It's always nil).

**Comment by bboyle18** [comment]
Hi @lucianocn 👋 

Thanks for getting in touch.
Can you tell me how long you were in the background for before you opened your app again?

Thanks

Brian

**Comment by lucianocn** [comment]
Hi @bboyle18 
I think the time does not interfere, but I tried 1~5 minutes and always `[Intercom unreadConversationCount]` was wrong.

**Comment by lucianocn** [comment]
@bboyle18 By the way `[Intercom unreadConversationCount]` never returns anything greater than 1, even with more unread messages.

**Comment by lucianocn** [comment]
@jtreanor I updated to 3.1.5 but still not working 100% properly, both situations.

**Comment by jtreanor** [comment]
@lucianocn Intercom does update the unread count (and fetch new messages) when your app comes to the foreground. The issue here seems to be that the count is wrong (as tracked in https://github.com/intercom/intercom-ios/issues/242). I'm closing this issue so that we can track it there. If you feel this is a separate issue, please let us know and we can re-open.
