### ISSUE TITLE
logging is enabled by default

### ISSUE THREAD

**Issue by salah-ghanim** [intercom/intercom-ios#277]
## Version info
  - Intercom for iOS version: 3.2.8
  - iOS version: 10.3.2

## Expected behavior
Logging is disabled unless enabled

## Actual behavior
calling logEvent without metadata writes this log message
`[Intercom] INFO - 'metaData' parameter was either nil, empty or not an NSDictionary. The event 'EVENT_NAME' will be logged without the metaData.`

## Steps to reproduce
 1. [Intercom logEventWithName:name metaData:nil];

**Comment by bboyle18** [comment]
Hi @salah-ghanim 
This is expected behaviour in this instance. The api method `[Intercom enableLogging]` turns on `debug` logging. 
The log in this instance is an `info` log where we explicitly highlight to customers  that the events they are logging have invalid data. 

Hope this clears things up.

Cheers

Brian

**Comment by salah-ghanim** [comment]
@bboyle18 I see. but would be nice to have such behaviour documented.

**Comment by bboyle18** [comment]
Thanks for the feedback. We'll take that into consideration 👍
