### ISSUE TITLE
Reduce library size

### ISSUE THREAD

**Issue by mhemmings** [intercom/intercom-ios#278]
We're doing some work on reducing our app size as it's gotten far too big. Inspecting our 3rd party libraries, Intercom is about 50-100x larger than our average library size 😬  Currently sits at around 46MB, now over half of our total app size.

I assume something odd is going on here?

**Comment by bboyle18** [comment]
Hi @mhemmings 👋 
Intercom.framework is ~47MB when in your project, but this is because it contains libs for all the possible framework types. Once you archive your app and it strips the unnecessary frameworks the size impact that Intercom has in your archived app is ~2.5MB.

Hope this clears things up.

Brian

**Comment by iad24** [comment]
@bboyle18  Before integrating the SDK, my app is around 25 to 30MB after archiving. With Intercom, it becomes 115 to 120MB. So fattttttt. How can it be 2.5MB as you say?

**Comment by jtreanor** [comment]
Hi @iad24 👋 

How are you measuring the size of you app? The size of the archive is not representative of what your users will see.

There is some information about measuring the size of you app in this doc: https://developer.apple.com/library/content/qa/qa1795/_index.html
