### ISSUE TITLE
400 errors with no other info on registerUser

### ISSUE THREAD

**Issue by jasonn85** [intercom/intercom-ios#282]
I suspect this has to do with our Segment Intercom integration and some kind of disagreement about user IDs and email addresses.  This problem appeared when we changed from using the user's email address as identification in Segment to using a user UUID.  We use `Intercom.registerUser(withEmail: email)` in the Intercom framework, only using it for chat.  This has always been email when using the Intercom framework.

This seems to happen 100% of the time for users who were once upon a time identified through Segment's Intercom integration by their login name.  We use UUID now in Segment.  The users seem broken forever in Intercom, not allowing identification by either method ever again.

Regardless of the cause, a naked 400 error cannot be correct behavior.

## Version info
  - Intercom for iOS version: 3.2.9
  - iOS version: 10.3.2

## Expected behavior
Either a successful login or some kind of useful error message.

## Actual behavior
`ERROR - Tried to update user but there was a network error (400) - Request failed: bad request (400)`

## Steps to reproduce
 1. Call `Intercom.registerUser(withEmail: email)` with a user who has also been identified through a Segment Intercom integration by email address and UUID at different times.  One such user: `jneel@zingle.me`
2. Cry

## Logs
`[Intercom] ERROR - Tried to update user but there was a network error (400) - Request failed: bad request (400)`

**Comment by harkin** [comment]
Woops, misclick. Thanks for the report, we'll look into this one tomorrow

**Comment by skylerwshaw** [comment]
@jasonn85 Intercom supports using `user_id` and `email` as unique user identifiers on all of our APIs. `user_id` is considered 'more unique' than `email` and as such you can have two users with different `user_id` values but identical `email` attributes. That is what is occurring with the 400 errors here. While we're looking into adding a descriptive 4xx error here, the root cause is that many of your users have duplicates with different `user_id` values and your mobile integration is not using `user_id`, which it should if that is your most unique attribute you're providing to Intercom. I'll not reveal user details here but you can search for `jneel@zingle.me` in your Intercom dashboard and find the two user profiles.

We'll work on the descriptive error situation this week.

**Comment by jasonn85** [comment]
But they are not different users.  They are the same person on different devices.  Is that not supported?

**Comment by skylerwshaw** [comment]
@jasonn85 If you search `jneel@zingle.me` in your Intercom app you will see two entries. Each has a unique `user_id` value. This means they are two users. If you want the same person on two devices to be seen as the same in Intercom, you need to pass the same `user_id` value if you are using `user_id` as your unique identifier, or `email` if you are only using `email`. In your case, both users have `user_id` values, so you must identify them by this attribute.

**Comment by jasonn85** [comment]
So, if the user_id is ever changed, that user is broken forever?

**Comment by skylerwshaw** [comment]
@jasonn85 I'm messaging you through Intercom to discuss user details. 👍

**Comment by skylerwshaw** [comment]
For future readers: We are now sending 409 errors for `MultipleMatchingUsers` errors instead of 400.
