### ISSUE TITLE
`hideMessenger()` has no completion block 👉 dysfunctional SFSafariViewController

### ISSUE THREAD

**Issue by philipengberg** [intercom/intercom-ios#294]
## Version info
  - Intercom for iOS version: `3.2.11`
  - iOS version: `10.3.3`

## Issue
We are sending out Intercom messages to our users which contain in-app deeplinks with attached web URLs in order to present an `SFSafariViewController` inside the app.
When the user taps the deeplink the Intercom messenger should obviously be hidden. But the `hideMessenger` function has no completion handler in order for us to know when this process is complete.

This means that doing this

```swift
Intercom.hideMessenger()

UIApplication.shared.keyWindow?.rootViewController?.present(SFSafariViewController(url: url), animated: true, completion: nil)
```

results in this:

![intercom](https://user-images.githubusercontent.com/1840093/29449952-1290d9aa-83fd-11e7-907f-d8616d9d8bec.png)

Reading around the Internet this seems to happen when you try to present the `SFSafariViewController` at the "wrong" time. But in this situation we have no way of knowing when that "right time" is.

Our deeplink to the `SFSafariViewController` works fine in the rest of our app when there is no Intercom view hierarchy presented.

## Suggestion
Add an optional completion block as an argument to the `hideMessenger()` function and an `isMessengerShown() -> Bool` function to know whether to try to hide it or not.

**Comment by philipengberg** [comment]
It's only an issue for the messenger. In the case below there is no problem:

![simulator screen shot 18 aug 2017 10 23 17](https://user-images.githubusercontent.com/1840093/29450678-ea2bb37e-83ff-11e7-8c3f-45b420f8d514.png)

**Comment by jtreanor** [comment]
Hi @philipengberg,

Thanks for the detailed write up on this. Your feedback that the Messenger should be closed when a deep link is pressed is absolutely valid and we will make this change in a future release.

However, there is a simple fix to your implementation that will remove the issue. Changing your code to something like this:
```
Intercom.hideMessenger()
if let rootViewController = UIApplication.shared.delegate?.window??.rootViewController {
    rootViewController.present(self, animated: true)
}
```

This is because it is not safe to assume that your app's primary window is the key window. In this case it is Intercom and there are other possibilities too. This or something similar will ensure that the view controller is presented within the context of your app's window and work as expected.

Let me know if any of this is unclear.

James

**Comment by philipengberg** [comment]
Thanks @jtreanor. I'm fully aware that you are presenting your own `UIWindow` when presenting the messenger. I therefore also tried to present on our own root window after hiding the messenger, but that resulted in even stranger behaviour than described above.

So the completion block would really be handy in this case 🙏

**Comment by bboyle18** [comment]
Hi @philipengberg 

Thanks for the feedback. We already have an`NSNotification` that fires when Intercom is hidden. Its `IntercomWindowDidHideNotification`. This will allow you to know when the Intercom window is hidden so that you can then present your own view controller.

Hope this helps.

Brian
