### ISSUE TITLE
Missing .dSYM file for framework when using Carthage

### ISSUE THREAD

**Issue by kevinkowalew** [intercom/intercom-ios#307]
## Version info
  - Intercom for iOS version: 3.2.8
  - iOS version: N/A

## Expected behavior
A .dSYM file is generated for the framework in the Archive.

## Actual behavior
A .dSYM file for the framework is missing from the Archive. 

## Steps to reproduce
Simply archive a project containing the framework and view the contents of the build.

## Logs 
N/A

**Comment by bboyle18** [comment]
Hi @kevinkowalew 👋 

Thanks for getting in touch.
We deliberately haven't included the `.dSYM` file with the framework because its quite large (~9MB) and we want to keep the framework size as small as possible.
However, if you want to include it you can grab it from the GitHub repo https://github.com/intercom/intercom-ios/tree/3.2.8/Intercom.framework.dSYM

Hope this helps

Brian

**Comment by kevinkowalew** [comment]
Good to know @bboyle18, thanks for the quick response!

**Comment by bboyle18** [comment]
No problem 👍
