### ISSUE TITLE
Error logging event

### ISSUE THREAD

**Issue by ivanmkc** [intercom/intercom-ios#314]
## Version info
  - Intercom for iOS version: 4.0.2
  - iOS version: 10.3

## Expected behavior
Logging completes successfully or at least tells me how to fix the issue.

## Actual behavior
[Intercom] ERROR - Tried to log an event but there was a network error - The operation couldn’t be completed. (Network request succeeded but the response was ignored error 0.)

## Steps to reproduce
 1. Log an event

It usually works fine, and sometimes shows that message. Identify verification is turned off.
On Intercom, it seems like the event still gets logged.

## Logs

**Comment by jtreanor** [comment]
Hi @ivanmkc,

The message here is `Network request succeeded but the response was ignored`. This actually means that the event was successfully logged. The response is ignored because `Intercom.reset()` has been called.

An example of when this could happen is logging a `Logged Out` event like this:

```
func logOut() {
    Intercom.logEvent(withName: "Logging Out")
    Intercom.reset()
}
```

It is worth verifying that your app does not call `Intercom.reset()` anywhere other than where the user logs out.

As this issue does not describe a bug with Intercom, I am closing it. Feel free to reach out through the Messenger on [intercom.com](https://www.intercom.com) if you would like to speak to our support team.

James
