### ISSUE TITLE
Add support for iPhone X

### ISSUE THREAD

**Issue by nathanjones** [intercom/intercom-ios#318]
## Version info
  - Intercom for iOS version: 4.0.3
  - iOS version: 11.0

## Expected behavior
That the background would extend to the edge of the screen and that Safe Area Layout Guides would be used to ensure UI elements aren't clipped when running Intercom on an iPhone X.

https://developer.apple.com/ios/human-interface-guidelines/overview/iphone-x

## Actual behavior
The background is clipped below the status bar. The buttons below the reply text input are clipped by the screen's rounded corners.

<img width="453" alt="intercom iphone x" src="https://user-images.githubusercontent.com/1918959/30940576-5ae4253c-a396-11e7-8ace-85960c5e741b.png">

## Steps to reproduce
 1. Launch Intercom using an iPhone X

## Logs
None

**Comment by jtreanor** [comment]
Hi @nathanjones,

Thanks for opening the issue.

We are aware that there is some work to do to prepare for the iPhone X launch. The updates will be shipped in plenty of time for the release 😄 

James

**Comment by nathanjones** [comment]
Thanks @jtreanor!

I figured you were aware of the design changes needed, but wanted to have a place where I and others can track progress either way.

**Comment by rajtharan-mallow** [comment]
I have also faced similar issue in iPhone X simulator.
Also attend the chat bubble padding issue in iPhone X since the padding value works fine in other devices and not fine with iPhone X as shown in the attached image.

1. UI in iPhone 5s with bottom padding as 40.
![other_ios_device](https://user-images.githubusercontent.com/23209069/31269930-f4327076-aa9f-11e7-8d8f-c556a555eb34.png)

2. UI in iPhone X with bottom padding as 40.
![iphone x - ui](https://user-images.githubusercontent.com/23209069/31270163-d5eefdc2-aaa0-11e7-98b9-e3371ec61f94.png)

**Comment by scottostlerch** [comment]
Any update on when we can expect a fix? We're two weeks away from iPhone X availability, and we need enough lead time to update Intercom, qa a release, and go through app store submission before then

**Comment by bboyle18** [comment]
Hi @scottostlerch We're actively working on this and it will be available later this week.

Brian

**Comment by calube** [comment]
Thanks guys @bboyle18  :)

**Comment by rvishal1991** [comment]
Hey Guys,

Any update on this?

Thanks

**Comment by bboyle18** [comment]
Hi @rvishal1991 
We will have an update this week that will contain iPhone X support. 

Brian

**Comment by bboyle18** [comment]
Hi @rvishal1991 @calube @scottostlerch @rajtharan-mallow @nathanjones 👋 

We have added iPhone X support in [Release 4.1.3](https://github.com/intercom/intercom-ios/releases/tag/4.1.3).

Cheers

Brian
