### ISSUE TITLE
Checking in pods difficult with huge file

### ISSUE THREAD

**Issue by alper** [intercom/intercom-ios#326]
We check our pods in in our project and after just upgrading Intercom it tells me that there is a file in there that's larger than 50MB. Checking in pods is kinda recommended usage, so it would be nice if we could keep using Intercom like that.

Any way on your side that you could reduce/remove the large file?

**Comment by jtreanor** [comment]
Hi @alper,

Unfortunately there is not much that we can do about this. The binary is this size because it contains all architecture slices as well as bitcode (the size impact on your app's download size is a very small fraction of this).

If you wish to continue checking in pods, I recommend using `git-lfs` (https://git-lfs.github.com/) to make dealing with large files much more manageable.

Let me know if you have any questions.

James
