### ISSUE TITLE
Release 4.1.3 not compatible with Xcode 8.3.3

### ISSUE THREAD

**Issue by andiradulescu** [intercom/intercom-ios#327]
This error is thrown on linking, using CocoaPods:

`ld: framework not found FileProvider for architecture x86_64`

**Comment by jtreanor** [comment]
Hi @andiradulescu,

You are seeing this error because 4.1.3 is the first version of Intercom that was built using Xcode 9. We must build with Xcode 9 in order to fully support iPhone X and iOS 11.

A quick search suggests there may be a possible workaround for the issue [here](https://stackoverflow.com/a/46483043).

As there is nothing we can do to fix this, I'm closing the issue.

**Comment by ppamorim** [comment]
Please add this problem on the documentation. I took a very long time to identify and can happen to other developers.
