### ISSUE TITLE
Experimental help center just shows loading spinner

### ISSUE THREAD

**Issue by mhemmings** [intercom/intercom-ios#352]
## Version info
  - Intercom for iOS version: 4.1.7
  - iOS version: 11.2.1

## Expected behavior
Help center loads with experimental header

## Actual behavior
Shows loading spinner indefinitely

## Steps to reproduce
 1. Integrate ` [Intercom presentHelpCenter]`
 2. Open help center

## Logs
Nothing obvious in logs

**Comment by bboyle18** [comment]
Hi @mhemmings 

Thanks for reporting this. 
We’re aware of this issue and have a fix in the works. 

Regards

Brian

**Comment by bboyle18** [comment]
Fixed in [release 4.1.8](https://github.com/intercom/intercom-ios/releases/tag/4.1.8)

Brian

**Comment by retsohuang** [comment]
Same issue here with 4.1.8 at iOS 11.2

**Comment by DaleCantwell** [comment]
@retsohuang do you have a button to open the messenger? Could you check on 4.1.8 if you see the loading spinner indefinitely and you close that screen then open the messenger then return to the help center if it loads. Potentially there is a config issue, that would help narrow it down.
Thanks

**Comment by retsohuang** [comment]
@DaleCantwell It still shows the loading spinner.

**Comment by askeland** [comment]
Hi! Since this feature is actually moved out of experimental and into production I tested this today. Got the same error and the reason for the forever spinner is that request to the help center are clocked by App Transport Security (ATS). Seems like it does not use proper HTTPS then. If you disable ATS, it works, but that is not a solution you put in production. Hope you guys can fix this, or at least provide instructions on what URL to whitelist in ATS to make it work 😄

**Comment by bboyle18** [comment]
Thanks for this info @askeland 
We're looking into a fix for this.

Brian

**Comment by bboyle18** [comment]
Hi @askeland 👋 
I can see that your help center is http://docs.jottacloud.com/
You'll need to add this URL to your whitelist for ATS to allow you to load the help center URL correctly.

We're going to update our docs to reflect this.
Let me know if this makes sense.

Brian

**Comment by askeland** [comment]
Aha, so it fails because our Help Center alias is not https. I was sure you made API requests directly towards your API endpoints. 

Will whitelist that URL then. Thanks for clearing that up. And I guess future devs will be happy for a mention of that in the docs 😉

**Comment by bboyle18** [comment]
At the moment we simply load the webpage in a webview. 😄

**Comment by askeland** [comment]
Was going to make a joke about that earlier 😬🤣 Anyway, looks descent, so why not

**Comment by raudabaugh** [comment]
I'm seeing the same behavior with our https-enabled help center: https://help.threadlearning.com

Adding the URL to the ATS whitelist worked. Don't mind that as a workaround for now, but could this be a bug affecting all custom domains, or something wrong with my config?

**Comment by bboyle18** [comment]
Hi @raudabaugh 👋 
Right now we have a bug in out server code that always returns 'http' instead of 'https`, thats why your help center fails to load unless you whitelist it.
We're working on a fix this week. After that, you won't need to whitelist.

I'll provide an update here when that fix is available.

Brian

**Comment by iShavgula-TacTill** [comment]
Hello,

I had the exact same bug, but now with 4.1.9 I'm having `Warning: Attempt to dismiss from view controller <ICMRootViewController: 0x110d9bcc0> while a presentation or dismiss is in progress!`.
I tried to present help center from different views, on did appear, on button click, etc...
Always the same error.

Any ideas? 

Thank you,
Giorgi

**Comment by mhemmings** [comment]
Hey @bboyle18 
Any update on this? I think we have the same problem.
Works fine with the test app, but fails in live which is on a custom domain.

**Comment by bboyle18** [comment]
Hi @mhemmings 👋 
We're making changes in our app at the moment to get custom domains working with `https`, but its not deployed yet.
In the meantime, you'll need to add your custom domain to your white list in your ATS settings. This is because custom domains get returned to us as `http` instead of `https` at the moment and therefore iOS blocks the loading of them unless you explicitly whitelist them.....this is the part we are fixing.

I'll update this issue once we have deploy our server changes.
Thanks for your patience.

Brian

**Comment by cavnit** [comment]
Hi @bboyle18,
Any update on this?

**Comment by bboyle18** [comment]
Hi @cavnit 
Please see my [previous commen](https://github.com/intercom/intercom-ios/issues/352#issuecomment-366706323)t for the latest on this issue.

Brian

**Comment by bboyle18** [comment]
Hi guys 👋 

We are moving all our issues support to our [Intercom Developers Hub available here](https://developers.intercom.com/docs/intercom-mobile-installation). We copied this issue with all the comments to our internal bug tracking tool. Whenever you would like an update, just reach out to us on our [Intercom Developer Hub](https://developers.intercom.com/docs/intercom-mobile-installation) and our Customer Support Engineers will help.

Thanks

Brian
