### ISSUE TITLE
Crash In -[ICMUserUpdateDeduper encodeWithCoder:]

### ISSUE THREAD

**Issue by Gevjan** [intercom/intercom-ios#357]
## Version info
- Intercom iOS SDK version: 4.1.3
## Steps to Reproduce
- Please refer to the attached Url with all the trails.
[http://crashes.to/s/34aea0f0943](http://crashes.to/s/34aea0f0943)

**Comment by bboyle18** [comment]
Thanks for reporting this @Gevjan 
We'll take a look and provide any updates here.

Brian

**Comment by bboyle18** [comment]
Hi @Gevjan 
Would you be able to provide a little more detail on when this crash happens please?
Is it at the same point in your app all the time or is it happening randomly?
Intercom is crashing your app because its trying to access a deallocated object. Any further information you can provide to us to help re-create the issue would be great 👍 

Thanks

Brian

**Comment by bboyle18** [comment]
HI @Gevjan 
I've made a change that should prevent this crash from occurring. This will be available in the next release.

Brian

**Comment by Gevjan** [comment]
Thanks @bboyle18 
I can't reproduce when crash is happened, 
Thanks I will wait for intercom next release.

**Comment by bboyle18** [comment]
We are moving all our issues support to our [Intercom Developers Hub available here](https://developers.intercom.com/docs/intercom-mobile-installation). We copied this issue with all the comments to our internal bug tracking tool. Whenever you would like an update, just reach out to us on our [Intercom Developer Hub](https://developers.intercom.com/docs/intercom-mobile-installation) and our Customer Support Engineers will help.

This issue will be fixed in the next release of Intercom.

Thanks

Brian
