### ISSUE TITLE
CFData leak with SocketRocket dependency

### ISSUE THREAD

**Issue by ajwhite** [intercom/intercom-ios#361]
## Version info
  - Intercom for iOS version: 3.2.12
  - iOS version: 9.0

## Expected behavior

`CFData` references should not endlessly grow

## Actual behavior

Exactly `22` references of `CFData` accumulate roughly every minute. The stack trace only shows back to `-[PodIntercom_SRRunLoopThread main]`, indicating something going on with the socket library.

## Steps to reproduce

With leaks, it's a bit hard to be particular here. It appears if you have Intercom configured and running. There's no direct calls being made to the library during this time period.

## Logs

![screen shot 2018-01-23 at 11 55 24 am](https://user-images.githubusercontent.com/656630/35289272-d621b2b4-0034-11e8-97d4-b806b31d4863.png)

**Comment by yinghang** [comment]
## Version info
Intercom for iOS version: 4.1.8
iOS version: 11.0
Expected behavior: CFData references should not climb in such a steep manner

## Actual behavior
Exactly 1 reference of CFData accumulate roughly every minute. Most of them can be traced back to 
`SocketStream` and the Intercom SDK.

## Steps to reproduce
1. Link Intercom to your Xcode project
2. Build and profile app
3. Run instruments and wait for 1 hour
4. Watch CFData references grow outta control


## Logs
<img width="698" alt="screen shot 2018-01-23 at 2 33 50 pm" src="https://user-images.githubusercontent.com/4490352/35299463-65bb2248-0053-11e8-8855-b4e8ad78539c.png">

**Comment by ajwhite** [comment]
Dropping a note on the captured reports above -- please note that the two reports show two different allocation categories and SDK versions. 

The First report shows allocations for `CFData`, and the second shows allocations for `CFData (store)`. We meant to submit the second report report for `CFData`, but this should still be helpful.

**Comment by bboyle18** [comment]
Hi @ajwhite @yinghang 👋 

We're looking into this issue but have been unable to recreate it yet. 
Can you confirm that when running instruments your app is sitting idle and not doing anything?
We are using SocketRocket v0.5.1.

Any extra info or data you can provide us with to help us get to the root cause of this would be great. 👍 

Thanks

Brian

**Comment by bboyle18** [comment]
Hi @ajwhite @yinghang 

This is was caused by our load balancer closing socket connections too frequently and SocketRocket not releasing memory from the dropped connection.
We've modified our load balancer settings so that we don't unnecessarily drop connections, so this issue should be fixed for you now. 
There no need to update to to the latest SDK to get this fix.

Cheers

Brian

**Comment by ajwhite** [comment]
Hi @bboyle18, thanks for looking into this. It's great to hear that the problem can be avoided by tweaking some server side configurations.

If I understand correctly, while the load balancer has been reconfigured to avoid dropping connections, SocketRocket is still vulnerable to retaining memory when a connection drops? 

To share some context about our application, it's ran in kiosk mode with an indefinite uptime (running 24/7). My understanding is that it would still be vulnerable to a subtle leak over a long period of time due to how SocketRocket manages closed connections. While these would be infrequent, it's important that our application and its dependencies are resilient under all circumstances.

**Comment by bboyle18** [comment]
Hey @ajwhite 
Yep, you're pretty much correct in your analysis. It looks like SocketRocket retains the memory of a dropped connection and Intercom was opening a new one to re-establish the connection. This happened every minute.
This was made worse by a bug in Intercom's code that failed to send a keep-alive ping under certain circumstances. It only started happening in the last few months when we made changes to our load balancer.
The load balancer has been tweaked so that connections won't be dropped like this again and we're putting a fix into the next release of the Intercom SDK to make sure it doesn't happen from the client side again.
With regards to your app being constantly open, this bug shouldn't show up again. Intercom will only open two socket connections when it starts. The only scenario where it will close and re-open a connection is if the server goes down or the client loses internet connection. 

Hope this make sense,

Brian

**Comment by ajwhite** [comment]
Hey @bboyle18, I appreciate you breaking down the problem. 

> The only scenario where it will close and re-open a connection is if the server goes down or the client loses internet connection.

Given that our application is up 24/7, network losses happen pretty frequently across the fleet of devices running Robin Rooms and can build up over time. Anecdotally, we have a tablet in the corner of the office where network strength is low and dips in and out hourly. From my understanding -- closing and re-opening a connection will still lead to a leak.

I'm looking to understand if Intercom will be able to address this underlying issue. We've unfortunately had to remove the integration in our latest app store release, which has created a bit of disparity in the reports we pull from Intercom. We're eager to bring reporting back to our iOS app, but we have to wait until the underlying problem is resolved.

I'm happy to provide any additional information that may be useful to you and your team.

**Comment by ajwhite** [comment]
On an additional note, I understand the problem is compounded by the fact that SocketRocket doesn't appear to be actively maintained, as the latest release was [nearly two years ago](https://github.com/facebook/SocketRocket/releases/tag/0.5.1).. ☹️ 

However, a stale patch appears to exist in https://github.com/facebook/SocketRocket/pull/504. If this SDK was open source, we would likely hot patch this in the meantime while a fix is in progress. If SocketRocket is no longer maintained, would you be open to forking the project, applying the patch, and including that in your next release? Alternatively if not, what can we do to apply that patch?

**Comment by bboyle18** [comment]
Thanks for clarifying your usage of Intercom @ajwhite 👍 
Yes, it appears that there may be an underlying memory load in SocketRocket that causes this. We would need to do further analysis to be 100% certain of the exact cause. We're also somewhat constrained by the fact that SocketRocket appears to be no longer maintained by Facebook.

We don't have capacity to look into this in detail in the next couple of weeks, but I can add this issue as a priority and it will be one of the things we pick up next.
I can take a look at that patch and yes, we would be open to forking the repo if it meant we could fix this issue.

I've noticed you opened a conversation in Intercom to track this issue as well. It might be better to continue the conversation and provide updates to you there.

**Comment by ajwhite** [comment]
Sounds great, @bboyle18. We're happy to help verify things on our end if that's helpful.

Will continue over Intercom/email
