### ISSUE TITLE
application:didReceiveRemoteNotification not called

### ISSUE THREAD

**Issue by saidmarouf** [intercom/intercom-ios#53]
When invoking `[Intercom registerForRemoteNotifications]`, I do not receive calls to `application:didReceiveRemoteNotification`. I'm assuming Intercom is swizzling and hijacking the call to `application:didReceiveRemoteNotification`.
Shouldn't the original method still be called by Intercom? This is very inconvenient as I'm not able to custom handle incoming notifications.

When removing the call to `[Intercom registerForRemoteNotifications]` (after invoking it once for a specific user), and start my app, I start receiving calls to `application:didReceiveRemoteNotification`.
Could you please verify this issue.

Testing with Intercom 2.0.7 on iOS 8.1.2.

Thanks

**Comment by idcuesta** [comment]
Hi @saidmarouf,

Our method `[Intercom registerForRemoteNotifications]` is not calling Apple's methods `[application registerForRemoteNotificationTypes:...]` or `[application registerUserNotificationSettings:...]`.

It is up to your app to decide what remote notifications you want to listen for (or user notification settings). All we do in that method is to swizzle some system methods, so when your app gets a device token from Apple we can get it too, in order to handle our own push messages to your app. 

We also ensure that we get the device token when a user begins a session, only if you have called our `registerForRemoteNotifications` method. We call Apple's methods to register for remote notifications with the same types the app has enabled at that moment.

Does this make sense in your use case? If you still have any doubt about how our push works, just let me know :)

Regards
Ignacio
