### ISSUE TITLE
Events on iOS app not showing up reliably.

### ISSUE THREAD

**Issue by jasonblood** [intercom/intercom-ios#54]
So in our app when we do certain things via our own api that might trigger a user event. E.g if I use our api to send a message to another user we might trigger an event regarding that (this is just an example). So when we do this in the app the event gets triggered (can see it in the intercom dashboard on the users account). But the event message is never displayed in the app unless we put the app in the foreground and re enter it. This makes the event message kind of pointless if it can pop up after such a delayed amount of time. I ensured that the user has been registered with intercom correctly on the app startup / log in. I was also able to receive regular messages I sent. I am also on the latest version of the iOS SDK. Thanks Jason

**Comment by adamkmccarthy** [comment]
Thanks Jason. To clarify, the cruz of the issue is the delay between SDK fired events and the receipt of the auto-message attached to that event? If you can contact us via Intercom directly with the events i can take a deeper look and see if something is up, usually the response is quick (i.e. immediate) but we've been doing some work in this area recently.  Thanks!

**Comment by jasonblood** [comment]
Hi @adamkmccarthy thanks I will get in touch via intercom. But just to clarify its not so much as a delay but the event doesn't seem to appear unless I make the app enter the background and bring it back to the foreground.

**Comment by adamkmccarthy** [comment]
Ah, apologies @jasonblood I think I understand you know. So if you `logEvent` at any stage, it seems as though it's not actually getting into Intercom until the next session has begun, is that right?
