### ISSUE TITLE
Keyboard is dismissing automatically without animating chat field

### ISSUE THREAD

**Issue by tariq235** [intercom/intercom-ios#80]
Issue is currently reproducible in simulator and tested in iphone 6 latest version.
Keyboard is dismissing automatically without animating chat field. Please check attached screenshot.
<img width="487" alt="screen shot 2015-08-03 at 12 23 33 pm" src="https://cloud.githubusercontent.com/assets/349211/9032284/af9fb3f2-39da-11e5-8276-8cbca6c72bca.png">

I have added keyboardWillHideNotification to check the trace.

#13	0x000000010f8ba1da in __80-[PodIntercom_IntercomConversationCollectionViewController resignFirstResponder]_block_invoke at /Users/intercom/TeamCity/buildAgent/temp/buildTmp/cocoapods-xrpdqlw2/Pods/IntercomConversationLayout/Pod/Classes/IntercomConversationCollectionViewController.m:411

**Comment by jtreanor** [comment]
Closing because through discussion with @tariq235, we have found this to be an issue with `DAKeyboardControl`, which he is using in his app.

I have put together a mod that could be made to `DAKeyboardControl` to allow it to work with Intercom: https://gist.github.com/jtreanor/9e7a98dafcf85b063375.
However, I strongly recommend against using `DAKeyboardControl` because it swizzles `addSubview:` which can lead to unpredictable behaviour throughout your app.
