### ISSUE TITLE
Carthage Support

### ISSUE THREAD

**Issue by flovilmart** [intercom/intercom-ios#81]
That one is an easy one.

When building your releases, just zip Intercom.framework in Intercom.framework.zip so Carthage can install it properly.

Thanks!

**Comment by adamkmccarthy** [comment]
thanks @flovilmart, we'll look into it for our next large point release :+1:

**Comment by jtreanor** [comment]
The [latest release](https://github.com/intercom/intercom-ios/releases/tag/2.3.3) has got `Intercom.framework.zip` attached. I have not tested it with Carthage but this may work for you.

**Comment by kylejm** [comment]
@jtreanor I can confirm that this works :+1:

**Comment by kylejm** [comment]
Whoops, spoke to soon.

Got this error:

```shell
Failed to read file or folder at /private/var/folders/9_/j9ns989d7zj7sf1mhwnlfkgc0000gn/T/carthage-archive.mRuhG3/__MACOSX/Intercom.framework
```

**Comment by kylejm** [comment]
Perhaps this is something to do with the _MACOSX framework being somewhat... empty? (it looks like it's missing stuff to me, at least).

**Comment by kylejm** [comment]
Has your team got an ETA for Carthage support? I'm trying to plan whether to include Intercom for our next release or wait a week or two for Carthage support.

**Comment by jtreanor** [comment]
Hey @kylejm 

Nice to chat to you again (We met at NSConf :smile:).

Unfortunately we have an issue stopping us from supporting Carthage right now. Carthage only supports [dynamic frameworks](https://github.com/Carthage/Carthage#supporting-carthage-for-your-framework), but dynamic frameworks only work on iOS 8+.

This means that we will not be able to support Carthage until Intercom for iOS drops iOS 7 support (many people still use this).

Because of this I suggest you go ahead and install Intercom without Carthage.

**Comment by kylejm** [comment]
Hey James! Yes, it's good to speak again :smile:! I knew it was you but I didn't think you'd remember me.. Haha!

No worries, I've been going about that last night and this morning :+1:. Thanks for the info!

**Comment by jtreanor** [comment]
You're welcome :smile: 

Feel free to reach out if you have any other questions.
